### ISSUE TITLE
Clicking on "out of bounds area" can result in not being able to drag

### ISSUE THREAD

**Issue by JoeSc** [worka/vanilla-js-wheel-zoom#12]
To reproduce
goto: https://worka.github.io/vanilla-js-wheel-zoom/demo-image.html
Click in the far upper right of the image box, so in the gray area.  Now try to drag the image, you should only be able to drag the image left-right, it should be "stuck" when trying to drag vertically.  I think that is because the transform is outside the bounds set in the draggable limits

I think the following change https://github.com/worka/vanilla-js-wheel-zoom/blob/8af2bfdca01794262c05ceecffbcf51fa431207c/src/wheel-zoom.js#L193

```javascript
            var maxAvailableLeft =
                (contentNewWidth - window.originalWidth) / 2 +
                content.correctX;

            var maxAvailableTop =
                (contentNewHeight - window.originalHeight) / 2 +
                content.correctY;

            if (contentNewLeft < -maxAvailableLeft)
                contentNewLeft = -maxAvailableLeft;
            if (contentNewLeft > maxAvailableLeft)
                contentNewLeft = maxAvailableLeft;

            if (contentNewTop < -maxAvailableTop)
                contentNewTop = -maxAvailableTop;
            if (contentNewTop > maxAvailableTop)
                contentNewTop = maxAvailableTop;
```

**Comment by worka** [comment]
I understanded problem. thk

**Comment by worka** [comment]
Done
