### ISSUE TITLE
Support for multiple WZooms on a single page

### ISSUE THREAD

**Issue by JoeSc** [worka/vanilla-js-wheel-zoom#13]
If I try to instantiate two different WZooms I get odd behaviour
```
A = WZoom.create('#thing1')
B = WZoom.create('#thing2')
```
Any idea how this could be fixed?

**Comment by worka** [comment]
Fixed it

**Comment by worka** [comment]
https://worka.github.io/vanilla-js-wheel-zoom/demo-images.html
