### ISSUE TITLE
How to avoid moving the whole page on the mobile?

### ISSUE THREAD

**Issue by IgorSerebryanskiy** [worka/vanilla-js-wheel-zoom#15]
Hi,

I'm trying to use this plugin on the page to zoom the image. But when I moving the zoomed image on the mobile it moves the whole HTML page, not the image only. Could you please fix it? Or help me how to do it?

And is it possible to zoom on the mobile browser using 2 fingers?

Thanks in advance.

Best regards,
Igor

**Comment by IgorSerebryanskiy** [comment]
https://user-images.githubusercontent.com/9727479/115310909-5722a300-a177-11eb-97fb-331763914a6f.mp4

It looks something like this.

**Comment by worka** [comment]
Hi.

I fixed the problem with scrolling on mobile devices.

Long time has been desire for realize a zoom with 2 fingers, but so far I am no possibility.

Так выпьем за то, чтобы наши желания совпадали с нашими возможностями.

**Comment by worka** [comment]
Done

**Comment by IgorSerebryanskiy** [comment]
Great. It works! Many thanks!

**Comment by worka** [comment]
I done zoom and pinch support, test pls :D
