### ISSUE TITLE
Image position at default

### ISSUE THREAD

**Issue by Sabin8peace** [worka/vanilla-js-wheel-zoom#22]
when i change minscale to 2 then it load image from center, how can i position it as y coordinate of image to zero, 
i mean default image load position of ycoordinate of image to 0, so that it will show the top portion of image.

**Comment by worka** [comment]
If I understand you correctly, do you want the initial positioning of the content to be set relative to the selected coordinate, and not just the center?

**Comment by worka** [comment]
I added alignContent option. Pls see ReadMe.
