### ISSUE TITLE
ZoomUP() to specific position

### ISSUE THREAD

**Issue by kennyzehn** [worka/vanilla-js-wheel-zoom#28]
Hey there, 
Thanks for this great lib!

We use this in a special way and have a small issue. 

Whenever the user is dragging the image we zoom in. On release we zoom out.

`
const zoom = WZoom.create(zoomImage, {
  dragScrollableOptions: {
      onGrab: function (e) {
          zoomImage.style.cursor = "grabbing";
          zoom.maxZoomUp();
      },
      onDrop: function () {
          if (zoom.content.currentScale === 1) {
              zoomImage.style.cursor = "grab";
          } else {
              zoomImage.style.cursor = "zoom-in";
          }
          zoom.maxZoomDown();
      },
  },
  zoomOnClick: false,
  disableWheelZoom: true,
  maxScale: defaultOptions.maxZoom,
  minScale: defaultOptions.minZoom
});
` 

It would be great to zoom into the image on this position where the user starts grabbing. 
Any idea how to solve it with the existing version? Or any chance to get this feature?

**Comment by worka** [comment]
```javascript
const zoom = WZoom.create(zoomImage, {
  dragScrollableOptions: {
    onGrab: function (event) {
      zoomImage.style.cursor = 'grabbing';
      zoom.maxZoomUpToPoint({ x: event.clientX, y: event.clientY });
    },
    onDrop: function () {
      if (zoom.content.currentScale === 1) {
        zoomImage.style.cursor = 'grab';
      } else {
        zoomImage.style.cursor = 'zoom-in';
      }
      zoom.maxZoomDown();
    }
  },
  zoomOnClick: false,
  disableWheelZoom: true,
  maxScale: defaultOptions.maxZoom,
  minScale: defaultOptions.minZoom
});
```

I updated my lib, see code. Remember that for touch devices, the coordinates are obtained differently.
