### ISSUE TITLE
Great, but does not work well on scaled page

### ISSUE THREAD

**Issue by wilschut** [worka/vanilla-js-wheel-zoom#3]
If a visitor has it's browser to scale 200% or so, the popup does not open with the full image in view.  And you can't get it completely in sight.
Can this be helped ?

**Comment by worka** [comment]
Hi, @wilschut. Sorry, I can`t understand what you mean

**Comment by wilschut** [comment]
Well, when browsing, you can scale the fonts in a website with [ctrl]+ mouse-wheel.
This way you can set it to 150% or so. But if you open the popup then, the picture does not show up completely: only the upper half and you vcan not get it totally in screen.
![examp](https://user-images.githubusercontent.com/33865110/80802208-048b5800-8baf-11ea-81d6-c1705cca4c3e.jpg)

**Comment by wilschut** [comment]
I zoomed in to 300% here...

**Comment by wilschut** [comment]
Nice of you to respond by the way. It's a cool script.

**Comment by worka** [comment]
"wheel-zoom" doesn't work there at all (in popup), or maybe your physical container size for image is larger than popup size?

**Comment by worka** [comment]
If you can then upload the code to the server, I'll try to see what’s the matter (I mean this http://btwilschut.nl/web/piepframeset.htm?piepstart.htm)

**Comment by wilschut** [comment]
I changed the url:
http://btwilschut.nl/web/gosstart.htm
But I think it's not your code that is the problem. I should not have raised the issue. Sorry for that.
I got it reasonably to work. Can I use your code in my (a little bit) commercial software for family trees ? It shows lists of thumbnails, and a click on them opens a popup with your wheelzoom control.

**Comment by wilschut** [comment]
see http://btwilschut.nl/web/gos000000.htm#1

**Comment by worka** [comment]
It works fine on your site for me even when scaling 300%+ (latest version Chrome)

Why you don`t use modern "popup methods" such as fancybox or similar (without jQuery), instead native browser popup window?

**Comment by wilschut** [comment]
Yes, I got it to work fine now. The tool I make is a winforms application that produces simple static websites that must work on all environments and servers and in all browsers, So I try to keep it as simple and old-school as possible. And this is only a really small item in the application so I can't spend much time on it. Especially gettings things to work correctly on firefox is a challenge. But I'm not clear on wheather or not I can use your code. I put your name and url in the .js script. Is that ok ?

**Comment by worka** [comment]
Ok, no problem.
