### ISSUE TITLE
Zoom mode on double click/tap

### ISSUE THREAD

**Issue by sant11h** [worka/vanilla-js-wheel-zoom#31]
Hello! I'm using your library and it's working great!
I saw you have an option to zoom fully on one click, but it's pretty confusing. Nowadays in most images previews we can "enter in zoom mode" when we double click/tap an image. 
It would be cool to have a configurable handler in your lib to do that, for example when we double tap the image it just does a zoomUp() and I think that's it.
Thanks!

**Comment by worka** [comment]
Hello. I didn't quite understand your question. You can implement your own dblclick handler. Or are you suggesting that the handling of this event should be "out of box" as it is the standard behavior in such libs?

**Comment by worka** [comment]
Hi. I agree with your proposal. If in the near time I have a free minute, I will seen with this issue. Or you can submit your PR.

You can also disable the default behavior and write your own dblclick handler.

Need to think about how to keep the old behavior for users of the library with minimal troubles for them.

**Comment by worka** [comment]
I did it )
