### ISSUE TITLE
Callback when max/min scale reached

### ISSUE THREAD

**Issue by sant11h** [worka/vanilla-js-wheel-zoom#34]
Hello! We appreciate your work for this lib.
I was wondering if you can add some sort of callback when the max or min scale is reached, for example:
`onMaxScaleReached(() => // I want to do something here)`

With this feature we give to the lib users the possibility of enabling or disabling the zoom in/out buttons when those events happen which is the use case that I need.
Thanks!

**Comment by worka** [comment]
Hello. You do not fit `rescale()` method for this? 

```javscript
rescale(instance) {
    // instance.content.minScale
    // instance.content.maxScale
    // instance.content.currentScale
}
```

Im a supporter of providing library clients with the most "raw" API that will remain concise (although this is no longer the case :)) and give clients more freedom to implement their needs, albeit on their own.

**Comment by sant11h** [comment]
Yes, that method did the trick.
Thanks for the support!

**Comment by worka** [comment]
It would be awesome if you could add to here common variant of your private solution for descendants. I will paste link to this issue in RM.
