### ISSUE TITLE
Make disableWheelZoom editable

### ISSUE THREAD

**Issue by ja1984** [worka/vanilla-js-wheel-zoom#37]
Nice lib, works really well with html content, great work buddy!

Got a quick question, would it be possible to add a function to toggle wheelZoom after the script have ben initialised? My use case is that I want to require the user to press CMD (on mac) or CTRL (on WIN) to be able to zoom on scroll, if the meta button is not presset I would like the mouse wheel to work like it normally do.

Cheers,
Jonathan

**Comment by worka** [comment]
Thanks buddy

How do you like this quick hack? As fast as your question :)

```javascript
const el = document.getElementById('myContent');
let zoom = false;

setTimeout(() => zoom = true, 5000);

el.addEventListener('wheel', event => !zoom && event.stopImmediatePropagation());

WZoom.create(el);
```
