### ISSUE TITLE
Zooming on mobile with two fingers is triggering zoomOnDblClick

### ISSUE THREAD

**Issue by v-flashpoint** [worka/vanilla-js-wheel-zoom#42]
Hi,

I think this is amazing, but I've been having a small problem integrating it into my site. I'd like to have it so the user can double click (or double tap) on mobile to zoom the picture all the way in, or zoom it all the way out. However, when users on mobile go to scale the image manually using two fingers, it's triggering the double tap event, and zooming it all the way in, essentially making it so people on mobile can't manually scale.

Is there an easy fix for this? I'd also love it if double tapping would always zoom the image all the way out if the image is already partially zoomed, and only zoom all the way in if the image is at its native scale. Not sure if this is possible with the current system!

Similarly, I'd also like to make it so users can single tap the image to get rid of it. However, that currently seems pretty tricky to do as just using listeners, as it's pretty hard to tap without dragging even slightly. I guess it'd be easy to do a workaround if you could get the start co-ordinates and end co-ordinates of the tap, so you could write a bit of leeway in, but I'm not sure if that sort of information about the image is freely available? (aha, never mind for this one - just found changedTouches[0].clientx in the event - I'm guessing I can use that)

Thanks for the great tool!

Ian

**Comment by worka** [comment]
Hello!

Your first question:

Looks like it's a bug

As a quick solution, I can suggest disabling image zooming per click and processing this action yourself using the API: `.maxZoomDown()` and `.maxZoomUpToPoint({x, y})`.

The second question: 

Can only be solved as I suggested
previously.

I didn't understand the third question :)

**Comment by worka** [comment]
I fixed the first bug, the rest is not a plugin problem
