### ISSUE TITLE
bootstrapt modal

### ISSUE THREAD

**Issue by TecHamlaoui** [worka/vanilla-js-wheel-zoom#43]
when i use the  <div id="myViewport" style="width:600px;height:600px;">
    <img id="myContent" src="https://via.placeholder.com/2400x1400" alt="image" />
</div>  inside bootstrap modal body the image get bigger and the zoom in and out won't work

**Comment by worka** [comment]
Hi

Perhaps you are initializing the plugin at the wrong moment? This must be done after the modal window has opened. And look at the styles to see what’s wrong

**Comment by AaronNGray** [comment]
@TecHamlaoui - was this issue resolved ?

**Comment by TecHamlaoui** [comment]
i make my custom modal box and it is working thank you
