### ISSUE TITLE
Missing some removeEventListener on move/drop when destroy instance 

### ISSUE THREAD

**Issue by bertrandg** [worka/vanilla-js-wheel-zoom#54]
Hi 👋 

First, thanks for this great lib I like play with it!

I recently find a behavior causing many js errors in my app, here it is:
Zoom & start moving an image and close preview during moving, so lib instance is killed using `wzoom.destroy()` but `move` & `drop` listeners [subscribed here](https://github.com/worka/vanilla-js-wheel-zoom/blob/211e94b4768b9d407f1bacde4acfedefa3898d0f/src/observers/DragScrollableObserver.js#L55) are not removed and cause errors like : 

```
wheel-zoom.min.js:357 Uncaught TypeError: Cannot read properties of null (reading 'x')
    at n2.value (wheel-zoom.min.js:357:26)
```

I think adding following code [there](https://github.com/worka/vanilla-js-wheel-zoom/blob/211e94b4768b9d407f1bacde4acfedefa3898d0f/src/observers/DragScrollableObserver.js#L40) could solve this :
```js
off(document, this.events.drop, this._dropHandler);
off(document, this.events.move, this._moveHandler);
```

**Comment by worka** [comment]
Hi. To be honest, I don't understand your scenario (tell me more). Why wasn't the `_dropHandler` method called? Your solution seems to work, but it seems not quite right.

**Comment by bertrandg** [comment]
hi,

Yes, no problem, here is more details about my usecase, hope it's better understandable :D

In my app I create & destroy instances of the lib multiple times during his lifecycle to preview images. 

It works well except in following cases:

- Grab & start moving image > inside lib `mousedown` call [_dragHandler](https://github.com/worka/vanilla-js-wheel-zoom/blob/211e94b4768b9d407f1bacde4acfedefa3898d0f/src/observers/DragScrollableObserver.js#L48)
- Then **BEFORE** drop image > inside lib `mouseup` call [_dropHandler](https://github.com/worka/vanilla-js-wheel-zoom/blob/211e94b4768b9d407f1bacde4acfedefa3898d0f/src/observers/DragScrollableObserver.js#L65)
- Make something like ESC key in my case to close preview > `wzoom.destroy()` > inside lib [destroy](https://github.com/worka/vanilla-js-wheel-zoom/blob/211e94b4768b9d407f1bacde4acfedefa3898d0f/src/observers/DragScrollableObserver.js#L38)

It end in a state where these [2 listeners](https://github.com/worka/vanilla-js-wheel-zoom/blob/211e94b4768b9d407f1bacde4acfedefa3898d0f/src/observers/DragScrollableObserver.js#L54) on `document` are never unsubscribed and make js errors

**Comment by bertrandg** [comment]
@worka thanks for the blazing fast fix 👍
