### ISSUE TITLE
Ability to be destroyed and attached to another div dynamically

### ISSUE THREAD

**Issue by anesuc** [worka/vanilla-js-wheel-zoom#8]
Hi,

So I have a carousel of images where a user clicks next to go to the next image. The zoom appears to work when I specify the active image element. But I tried setting the variable to null (to make sure the garbage collection removes it) and re-initialising it when image switches to next one but seems to break in this scenario. Possibility of a .destroy() method?

**Comment by worka** [comment]
I done this, pls, check and test

**Comment by anesuc** [comment]
That fixed it! Thanks for the fast response!
